"""Adapter contracts and hardware-free reference adapters for OSIP."""

from omnisense_adapters.channels import CHANNEL_MESSAGE_TYPES, channel_id_for_bus_topic
from omnisense_adapters.interfaces import (
    AdapterMetadata,
    AdapterRole,
    AdapterRunResult,
    OSIPSourceAdapter,
)
from omnisense_adapters.jsonl import DEFAULT_ALLOWED_MESSAGE_TYPES, JSONLOSIPSourceAdapter
from omnisense_adapters.mqtt import (
    MqttBridgeCodec,
    MqttDecodedRecord,
    MqttInboundBridge,
    MqttInboundMessage,
    MqttMessageSource,
    MqttOutboundBridge,
    MqttPublishRecord,
    MqttPublishTransport,
    MqttTopicMapper,
    ensure_mqtt_topic,
)
from omnisense_adapters.nats import (
    NatsBridgeCodec,
    NatsDecodedRecord,
    NatsInboundBridge,
    NatsInboundMessage,
    NatsMessageSource,
    NatsOutboundBridge,
    NatsPublishRecord,
    NatsPublishTransport,
    NatsSubjectMapper,
    ensure_nats_subject,
)
from omnisense_adapters.ros2 import (
    ROS2_JSON_MESSAGE_TYPE,
    Ros2BridgeCodec,
    Ros2DecodedRecord,
    Ros2InboundBridge,
    Ros2InboundMessage,
    Ros2MessageSource,
    Ros2OutboundBridge,
    Ros2PublishRecord,
    Ros2PublishTransport,
    Ros2TopicMapper,
    ensure_ros2_namespace,
    ensure_ros2_topic_name,
)

__all__ = [
    "CHANNEL_MESSAGE_TYPES",
    "DEFAULT_ALLOWED_MESSAGE_TYPES",
    "AdapterMetadata",
    "AdapterRole",
    "AdapterRunResult",
    "JSONLOSIPSourceAdapter",
    "MqttBridgeCodec",
    "MqttDecodedRecord",
    "MqttInboundBridge",
    "MqttInboundMessage",
    "MqttMessageSource",
    "MqttOutboundBridge",
    "MqttPublishRecord",
    "MqttPublishTransport",
    "MqttTopicMapper",
    "NatsBridgeCodec",
    "NatsDecodedRecord",
    "NatsInboundBridge",
    "NatsInboundMessage",
    "NatsMessageSource",
    "NatsOutboundBridge",
    "NatsPublishRecord",
    "NatsPublishTransport",
    "NatsSubjectMapper",
    "OSIPSourceAdapter",
    "ROS2_JSON_MESSAGE_TYPE",
    "Ros2BridgeCodec",
    "Ros2DecodedRecord",
    "Ros2InboundBridge",
    "Ros2InboundMessage",
    "Ros2MessageSource",
    "Ros2OutboundBridge",
    "Ros2PublishRecord",
    "Ros2PublishTransport",
    "Ros2TopicMapper",
    "channel_id_for_bus_topic",
    "ensure_mqtt_topic",
    "ensure_nats_subject",
    "ensure_ros2_namespace",
    "ensure_ros2_topic_name",
]
