"""Transport-agnostic message bus contracts for OmniSense Runtime."""

from omnisense_bus.interfaces import AsyncMessageBus, Subscription
from omnisense_bus.memory_bus import (
    BackpressureError,
    InMemoryBus,
    InMemorySubscription,
    SubscriptionClosedError,
)
from omnisense_bus.messages import BusMessage
from omnisense_bus.qos import QOS_BY_CHANNEL, QoSProfile, qos_for_channel
from omnisense_bus.qos_mapping import (
    AdapterKind,
    AdapterQoSMapping,
    Mqtt5QoSMapping,
    NatsQoSMapping,
    Ros2DDSQoSMapping,
    map_qos_profile,
    map_to_mqtt5,
    map_to_nats,
    map_to_ros2_dds,
)
from omnisense_bus.replay import ReplayRecord, load_jsonl_trace, replay_jsonl
from omnisense_bus.topics import (
    InvalidTopicError,
    action_command_filter,
    action_command_topic,
    action_contracts_topic,
    action_proposals_topic,
    action_result_filter,
    action_result_topic,
    adapter_heartbeat_filter,
    adapter_heartbeat_topic,
    build_topic,
    context_update_filter,
    context_update_topic,
    ensure_valid_topic,
    event_detected_filter,
    event_detected_topic,
    model_capabilities_topic,
    percept_filter,
    percept_topic,
    profile_safety_case_filter,
    profile_safety_case_topic,
    topic_matches,
)

__all__ = [
    "AsyncMessageBus",
    "AdapterKind",
    "AdapterQoSMapping",
    "BackpressureError",
    "BusMessage",
    "InMemoryBus",
    "InMemorySubscription",
    "InvalidTopicError",
    "Mqtt5QoSMapping",
    "NatsQoSMapping",
    "QOS_BY_CHANNEL",
    "QoSProfile",
    "ReplayRecord",
    "Ros2DDSQoSMapping",
    "Subscription",
    "SubscriptionClosedError",
    "adapter_heartbeat_filter",
    "adapter_heartbeat_topic",
    "action_command_filter",
    "action_command_topic",
    "action_contracts_topic",
    "action_proposals_topic",
    "action_result_filter",
    "action_result_topic",
    "build_topic",
    "context_update_filter",
    "context_update_topic",
    "ensure_valid_topic",
    "event_detected_filter",
    "event_detected_topic",
    "load_jsonl_trace",
    "map_qos_profile",
    "map_to_mqtt5",
    "map_to_nats",
    "map_to_ros2_dds",
    "model_capabilities_topic",
    "percept_filter",
    "percept_topic",
    "profile_safety_case_filter",
    "profile_safety_case_topic",
    "qos_for_channel",
    "replay_jsonl",
    "topic_matches",
]
